# Project: Teddi
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = Teddi_private.res
OBJ  = ../Animation.o ../Bullet.o ../Creature.o ../Dummy.o ../EventCore.o ../FontCore.o ../GraphicCore.o ../Keyboard.o ../LogicCore.o ../main.o ../Map.o ../math.o ../Object.o ../Placeable.o ../Player.o ../Scorebar.o ../Sound.o ../SoundCore.o ../Sprite.o ../Sync.o ../Texture.o ../Weapon.o $(RES)
LINKOBJ  = ../Animation.o ../Bullet.o ../Creature.o ../Dummy.o ../EventCore.o ../FontCore.o ../GraphicCore.o ../Keyboard.o ../LogicCore.o ../main.o ../Map.o ../math.o ../Object.o ../Placeable.o ../Player.o ../Scorebar.o ../Sound.o ../SoundCore.o ../Sprite.o ../Sync.o ../Texture.o ../Weapon.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" -mwindows -lmingw32 -lSDLmain -lSDL -lSDL_mixer -lSDL_ttf -lopengl32  
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include" 
BIN  = Teddi.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS) -Dmain=SDL_main  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Teddi.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "Teddi.exe" $(LIBS)

../Animation.o: ../Animation.cpp
	$(CPP) -c ../Animation.cpp -o ../Animation.o $(CXXFLAGS)

../Bullet.o: ../Bullet.cpp
	$(CPP) -c ../Bullet.cpp -o ../Bullet.o $(CXXFLAGS)

../Creature.o: ../Creature.cpp
	$(CPP) -c ../Creature.cpp -o ../Creature.o $(CXXFLAGS)

../Dummy.o: ../Dummy.cpp
	$(CPP) -c ../Dummy.cpp -o ../Dummy.o $(CXXFLAGS)

../EventCore.o: ../EventCore.cpp
	$(CPP) -c ../EventCore.cpp -o ../EventCore.o $(CXXFLAGS)

../FontCore.o: ../FontCore.cpp
	$(CPP) -c ../FontCore.cpp -o ../FontCore.o $(CXXFLAGS)

../GraphicCore.o: ../GraphicCore.cpp
	$(CPP) -c ../GraphicCore.cpp -o ../GraphicCore.o $(CXXFLAGS)

../Keyboard.o: ../Keyboard.cpp
	$(CPP) -c ../Keyboard.cpp -o ../Keyboard.o $(CXXFLAGS)

../LogicCore.o: ../LogicCore.cpp
	$(CPP) -c ../LogicCore.cpp -o ../LogicCore.o $(CXXFLAGS)

../main.o: ../main.cpp
	$(CPP) -c ../main.cpp -o ../main.o $(CXXFLAGS)

../Map.o: ../Map.cpp
	$(CPP) -c ../Map.cpp -o ../Map.o $(CXXFLAGS)

../math.o: ../math.cpp
	$(CPP) -c ../math.cpp -o ../math.o $(CXXFLAGS)

../Object.o: ../Object.cpp
	$(CPP) -c ../Object.cpp -o ../Object.o $(CXXFLAGS)

../Placeable.o: ../Placeable.cpp
	$(CPP) -c ../Placeable.cpp -o ../Placeable.o $(CXXFLAGS)

../Player.o: ../Player.cpp
	$(CPP) -c ../Player.cpp -o ../Player.o $(CXXFLAGS)

../Scorebar.o: ../Scorebar.cpp
	$(CPP) -c ../Scorebar.cpp -o ../Scorebar.o $(CXXFLAGS)

../Sound.o: ../Sound.cpp
	$(CPP) -c ../Sound.cpp -o ../Sound.o $(CXXFLAGS)

../SoundCore.o: ../SoundCore.cpp
	$(CPP) -c ../SoundCore.cpp -o ../SoundCore.o $(CXXFLAGS)

../Sprite.o: ../Sprite.cpp
	$(CPP) -c ../Sprite.cpp -o ../Sprite.o $(CXXFLAGS)

../Sync.o: ../Sync.cpp
	$(CPP) -c ../Sync.cpp -o ../Sync.o $(CXXFLAGS)

../Texture.o: ../Texture.cpp
	$(CPP) -c ../Texture.cpp -o ../Texture.o $(CXXFLAGS)

../Weapon.o: ../Weapon.cpp
	$(CPP) -c ../Weapon.cpp -o ../Weapon.o $(CXXFLAGS)

Teddi_private.res: Teddi_private.rc 
	$(WINDRES) -i Teddi_private.rc --input-format=rc -o Teddi_private.res -O coff 
